### PR TITLE
Implement RSS feed for latest commits

### LINKED ISSUE #61: RSS Feed
An RSS feed of changes would be great, (maybe even one for ALL, and ones for each platform ?)

### PR DESCRIPTION
**Pull request by Xenopathic**
Quite simple, just presents an RSS feed on `rss.php` that lists the latest commits, with a link back to the main page. RSS link uses GET parameter '?commit=commithash' to make each link unique, and to lay the foundation for highlighting commit changes in the matrix.

New Composer libraries: suin/php-rss-writer to aid creating the RSS tree, and symfony/http-foundation so that parsing GET/POST parameters and request headers is much easier.

Fixes #61

### CODE REVIEW

**Comment by Xenopathic** [comment]
Now we've got a banner! Hope you guys like it (or at least like it enough to make changes to it rather than throw it all away :smile:)

**Comment by MightyCreak** [comment]
I apparently don't have one of the font you're using in the banner. It might be better to export a PNG from the SVG instead?

capture d ecran de 2015-06-11 19-39-32

**Comment by MightyCreak** [comment]
We might want to link directly to the git page?

Like this:
http://cgit.freedesktop.org/mesa/mesa/commit/docs/GL3.txt?id=d9109cc2111a765f09fbf54072b77528e35c156d

Instead of this, because we don't see anything special regarding the specified commit:
http://localhost/mesamatrix/http/?commit=d9109cc2111a765f09fbf54072b77528e35c156d

Or we could highlight the commit in the list. Or (even better) unfold the commit line to show the commit description (but that would need some more code ;))

**Comment by Xenopathic** [comment]
Oh, `$commitWeb` was my initial implementation, which did link directly to Mesa git. I decided to change it because a user using the RSS feed *wants* to use Mesamatrix, not the cgit frontend directly, so we should link back to the matrix (with the ability to highlight changes, coming soon!)

**Comment by Xenopathic** [comment]
I've rendered the text into paths, so fonts no longer matter. I've also changed the spacing of the monospace characters.

**Comment by MightyCreak** [comment]
You're a machine! :D

If the highlighting is coming then it seems right to me. Do you want to keep the `$commitWeb` line?

**Comment by Xenopathic** [comment]
@MightyCreak Yes, I'll remove the `$commitWeb` line, not much point keeping it now.

Are you happy with the rest of this change though? If you don't like some part of the banner, I'll change it :smile: Also, it's quite big (over 30kB), we might need to simplify it...

**Comment by MightyCreak** [comment]
Yep! The new banner is cool and the RSS is a good idea!

Is there also an Atom plugin? What's the status of the Atom format nowadays? Is it abandoned or still advised as a better feeding format?

Don't you think it would be better to have PNGs instead of SVGs (but keep the SVGs as raw files)? SVG rendering is quite browser dependent, isn't it?

**Comment by Xenopathic** [comment]
@MightyCreak Nice, glad you like the banner :smile:

Personally, I'm not interested in implementing Atom - any browser that supports it will support RSS, and it seems many websites only expose RSS feeds now - looks like Atom has died a silent death.

PNGs have the advantage of being the same on any device, browser or platform, so we might want to switch to that (in a future PR, perhaps). SVG support seems pretty widespread now (http://caniuse.com/#feat=svg).

As for using http-foundation for the URL cache - I'm not sure that's what the library is designed for, but if you have an alternative implementation of what we have already then I'll review it :smile:

**Comment by MightyCreak** [comment]
Ok for Atom, if no one uses it anymore, there is no interest in supporting it.

For the PNG, it's more about the rendering problems than the browsers support. I think it's interesting to use SVG if you need to dynamically create it or edit it (with Javascript for instance), or if you want to have a scalable raw image. That's why I think it would be nice to convert these SVG to PNG in this PR. Or I can do it in a following PR if you want.

**Comment by Xenopathic** [comment]
@MightyCreak I see your point. Let's do it in another PR (perhaps with a Makefile or something to regenerate it? :smile:)

**Comment by MightyCreak** [comment]
Deal!

(Maybe a Makefile is a bit too much for just 2 images that we won't change that much... ;))

**Comment by stuaxo** [comment]
This is really nice !

There's a slight usability bug if the window is made small (on my screen, 1/2 width will do it) - the RSS button becomes obscured by the the 'fork me on github' making it impossible to click.

**Comment by MightyCreak** [comment]
Yep, I'll try to fix that. It's a problem I got on mobile mainly.

Thanks!

**Pull request merged**
