### PR TITLE
Add Asahi to Rusticl

### PR DESCRIPTION
**Pull request by karolherbst**
upstream MR: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/24948

### CODE REVIEW

**Comment by MightyCreak** [comment]
Seems good, though I don't see any mention of asahi in the Rusticl extensions, will the features.txt file be updated soon?

**Comment by karolherbst** [comment]
> fyi, it's going to land in the main branch via this MR: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/25052

and it got merged

**Comment by MightyCreak** [comment]
The issue, if I merge this MR, is that asahi will be considered as complete as the panfrost driver.

This is because most Rusticl extensions are just `DONE` and as per [the legend](https://gitlab.freedesktop.org/mesa/mesa/blob/main/docs/features.txt#L8-10), it means that "The extension is done for Mesa and no implementation is necessary on the driver-side".

I don't know if this is true or not... Is mesa the only necessary component in implementing these extensions?

**Comment by karolherbst** [comment]
> The issue, if I merge this MR, is that asahi will be considered as complete as the panfrost driver.
> 
> This is because most Rusticl extensions are just `DONE` and as per [the legend](https://gitlab.freedesktop.org/mesa/mesa/blob/main/docs/features.txt#L8-10), it means that "The extension is done for Mesa and no implementation is necessary on the driver-side".
> 
> I don't know if this is true or not... Is mesa the only necessary component in implementing these extensions?

yes. The main design goal I had with rusticl was to implement as much as possible driver independently. And only some of those features actually require mesa internal optional features. The baseline is OpenGL compute shaders and that already includes quite a lot.

And so far Asahi didn't implement much of the optional things, so there is also not much to expect there. And it's already like 95%+ of the OpenCL 3.0 CTS and we'll deal with those left over bugs, but those problems are just general shortcomings of the asahi driver and not really specific to a OpenCL feature.

Saying that.. asahi doesn't support `cl_khr_3d_image_writes` so I think we'll have to fix that up on the mesa side.

**Comment by MightyCreak** [comment]
ok, well let's merge it and see what happens! :sweat_smile:

**Comment by MightyCreak** [comment]
@karolherbst there was an issue, can you check this fix please? #293

**Pull request merged**
