### PR TITLE
Add etnaviv driver

### PR DESCRIPTION
**Pull request by MightyCreak**
Add the etnaviv driver. Don't add the vc4 and vc5 drivers as requested in PR #136 simply because these drivers aren't mentioned in the features.txt file. I only add drivers that are listed in this file (because it shows that the devs want to track these as well).

### CODE REVIEW

**Comment by mirh** [comment]
As I said in #122, can't you start to scrap the driver code itself?
[Unless](https://github.com/MightyCreak/mesamatrix/issues/128#issuecomment-516082076) you want to contribute to features.txt yourself, it seems far more reliable.

**Comment by MightyCreak** [comment]
I would rather not parse C code, it's a Pandora box :smile: 

I've investigated a little though and ran this command:
```bash
grep -r 'ctx->Extensions\..*[ a-zA-Z0-9]=[ a-zA-Z0-9]' src/mesa/drivers/
```

This allows to get all the line looking like that:
```
ctx->Extensions.EXT_texture_filter_anisotropic = true;
```

But from what I understand, it is far from accurate. The Intel i965 directory counts 192 lines (on a total of 225 extensions done for this driver from what mesamatrix.net tells). It's not that bad and we could consider that the diff is because of hardware subtleties or maybe because some common extensions are defined somewhere else in the code. But when looking at the radeon directory, there are only 18 lines, clearly far from what this driver currently supports.

So I'm not so sure scrapping the C code is the best idea. Unless maybe you have an explanation for these numbers, I'll be glad to understand.

**Comment by MightyCreak** [comment]
That being said, if a mesa dev here could point me to a way to compile and generate some kind of features.txt (or xml) directly based on the code, that would be a great idea!

But as long as I don't know if it's possible to get all these informations from the code (and where to get them), I'd rather not get my hand into that.

**Comment by MightyCreak** [comment]
Hmm... The more I look at the code, the more it seems possible... I've opened an issue: #150

**Pull request merged**
