### PR TITLE
Add freedreno to Rusticl

### PR DESCRIPTION
**Pull request by rmader**
Mesa MR: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/30835

### CODE REVIEW

**Comment by rmader** [comment]
@MightyCreak gentle ping, now that 24.3 has been released (freedreno Rusticl support is now in stable) :)

**Comment by rmader** [comment]
@MightyCreak  Thanks for landing this! I noticed that freedreno does not show up on https://mesamatrix.net/#RusticlOpenCL yet and quickly wanted to check: is that because the code has not been deployed yet to the server? Or did I get something wrong here?

**Comment by MightyCreak** [comment]
@rmader yep, I'll deploy it this weekend, sorry for the delay :wink:

**Comment by MightyCreak** [comment]
Done! :wink:

**Pull request merged**
