### PR TITLE
Add panfrost driver

### PR DESCRIPTION
**Pull request by DidntRead**
Add panfrost driver. The color was taken from the arm logo on the arm website.

### CODE REVIEW

**Comment by MightyCreak** [comment]
Thanks for your contribution! I pulled your branch to make tiny modifications: I lightened the color, and changed the text from "Arm" to "ARM" and it is now merged in master!

**Comment by alyssarosenzweig** [comment]
FWIW, 'Arm' is sentence-case since 2017 http://linuxgizmos.com/arm-becomes-arm-or-is-it-arm/

**Comment by MightyCreak** [comment]
Oh you're completely right, I'm sorry. I looked at the wrong website apparently. I'll change that later. Thank you for correcting me 😉

**Comment by Olf0** [comment]
[Thank you](https://github.com/MightyCreak/mesamatrix/commit/170daab7ed9dc590b3a112a424a05831f2b11417#commitcomment-43756769) for denoting the [modern spelling of the "arm" company / holding](https://en.wikipedia.org/wiki/Arm_Ltd.#Name) and disambiguation to the "[ARM architecture](https://en.wikipedia.org/wiki/ARM_architecture)".

**Pull request closed without merging**
