### PR TITLE
Prevent filemtime() warning if FETCH_HEAD doesn't exist

### PR DESCRIPTION
**Pull request by Xenopathic**
Fallback to checking the mtime of the whole directory, which is close enough.

### CODE REVIEW

**Comment by MightyCreak** [comment]
Is it possible that the HEAD doesn't exist?

**Comment by Xenopathic** [comment]
Not as far as I'm aware, but the only time FETCH_HEAD doesn't exist is when the repo has been first cloned (and not updated via a fetch), so the timestamp on HEAD will be the same as on the directory.

**Comment by MightyCreak** [comment]
I'd rather send an error if that's the case. Something like "FETCH_HEAD doesn't exist, did you run `mesamatrixctl fetch`?"

**Comment by Xenopathic** [comment]
So we don't expect the installation to just work after running `mesamatrixctl setup`? The README suggests otherwise

**Comment by MightyCreak** [comment]
True... I don't think we need to have a fallback for everything though. Simply add the `fetch` command line in the README would be enough.

If we want to be sure, we can test if the FETCH_HEAD file exists before even starting the whole parsing.

**Comment by MightyCreak** [comment]
Oups, wrong button ;)

**Comment by MightyCreak** [comment]
I took inspiration from you PR to solve this issue (I take HEAD if FETCH_HEAD doesn't exist).

Here is the commit: 90e22c22827bcf401dddb915e861f9b403417c34

**Pull request closed without merging**
