### PR TITLE
Check the oldest commit and fallback if unreachable

### PR DESCRIPTION
**Pull request by Xenopathic**
If the oldest commit isn't available (e.g. it is outside the clone
depth) fallback to the oldest commit available instead.

### CODE REVIEW

**Comment by Xenopathic** [comment]
A proper fix for #72

**Comment by MightyCreak** [comment]
Here too, I took inspiration from your work and removed completely the `oldest_commit` and the `depth` config parameters. I also only lists the commits for GL3.txt. Too bad it's not possible to do a pipe (`|`) with ProcessBuilder in Symfony, I had to do the `head -n 1` manually using `strtok`.

Here is the commit: 90e22c22827bcf401dddb915e861f9b403417c34

**Comment by Xenopathic** [comment]
This will still break, it's also going to be a lot slower, since the number of commits on the `master` branch is wayyy more than 10000 (the previous value of `depth`), and also the parser will break if it tries to parse a commit where the GL3.txt format is different than expected. That was the whole purpose of the `oldest_commit` config value, a fundamental limit on what the parser can support (although in retrospect it should have been a class constant on OglParser, not a config value).

**Comment by MightyCreak** [comment]
But it doesn't break ;)

I tried both locally and on the mesamatrix.net server and there are no warning or error during the setup/fetching/parsing.

It's not that slow either compared to before. Getting the whole tree, whether it's limited in depth or not, it still take time (less than a minute anyway) and it's a one time thing (i.e. setup). And now I only get the depth of the GL3.txt file which is not that big: 305 commits (`git rev-list master -- docs/GL3.txt | wc -l`). As for the rest, now it's incremental, so it only takes the time to parse the few new commits that happen not very frequently and then merge everything together, which takes 10 seconds max.

I think that the simplicity it offers is better than the few seconds it adds, don't you think?

**Comment by MightyCreak** [comment]
Of course, if you see that it does break something, I can easily revive the depth and/or the oldest_commit features.

**Pull request closed without merging**
