### PR TITLE
Less aggressive colors for the extensions states.

### PR DESCRIPTION
**Pull request by MightyCreak**
@Xenopathic I softened a bit the colors of the states. Tell me what you think ;)

### CODE REVIEW

**Comment by Xenopathic** [comment]
:-1: it looks whitewashed.

**Comment by Xenopathic** [comment]
But I do agree the current colours are very aggressive. Perhaps the red and orange need to be toned down? I think the green is quite nice as it is. Just be careful not to whitewash the colours - change them to a different shade

**Comment by Xenopathic** [comment]
A balance needs to be struck between aggressiveness and how the incomplete features stand out. Perhaps you could investigate swapping out the red for a deep shade of blue or something?

**Comment by Xenopathic** [comment]
Or how about: #992222 for the red colour? You'd need to adjust the orange to match though

**Comment by MightyCreak** [comment]
I kinda like the new green, but I agree that the new orange and the new red are a bit too whitewashed. I'll try to find other colors.

**Comment by MightyCreak** [comment]
@Xenopathic I think I've got something good here. It's less acid than before, yet still strong, not whitewashed colors.

Before:
matrix_before

After:
matrix_after

**Comment by Xenopathic** [comment]
Ooh, an update! Hmm, I definitely like this better than before, but the green is now too dull :laughing: It *should* stand out - users want to see what extensions have been implemented. Also, I think the orange should be reverted to how it was - the 'in progress' ones are surely the most important to see?

**Comment by MightyCreak** [comment]
If you compare to the previous colors, the new ones are definitely more dull, but without comparison they are still pretty distinct and flashy. I think differences between the new colors are actually the same as differences between old colors, just a bit less aggressive to not break your eye if you look at the site in the dark ;)

**Comment by Xenopathic** [comment]
Remember that the background is white. Perhaps we want to change that? A white screen is more of a blazing supernova in a dark room than some red and green...

**Comment by MightyCreak** [comment]
Hehehe yeah I noticed when I wrote my comment, but anyway, I think these colors are a good compromise. Peppy yet not too acid.

**Comment by Xenopathic** [comment]
Try the following, and see if you like it:

* Red: `#D74533`
* Orange: `#E7A22B`
* Green: `#8FEA3B`

screenshot - 220415 - 09 16 35

**Comment by MightyCreak** [comment]
I'll try that, but it's not very different from the original colors when I compare the two screenshots ;)

**Comment by MightyCreak** [comment]
I tested, with the gradient, the oranges are basically the same. And if I tone down a little the green, then the red is too peppy with your settings.

So I'll merge the PR with the current colors. I feel it a good compromise ;)

Thanks!

**Comment by Xenopathic** [comment]
That sounds reasonable :) You know me, if I think it could be improved, I'll send a PR your way :laughing:

**Comment by MightyCreak** [comment]
I count on you for that ;)

**Pull request merged**
