### PR TITLE
Add VC4,VC5 and Vivante GPUs

### PR DESCRIPTION
**Pull request by robertfoss**

### CODE REVIEW

**Comment by MightyCreak** [comment]
Thanks for the PR.
I'll merge it as soon as the features.txt file starts to track these drivers.

**Comment by volkertb** [comment]
Now that @anholt has renamed the VC5 driver to V3D (in preparation for VC6 support in the same driver), shouldn't the change in this PR be updated to account for that as well? See https://www.phoronix.com/scan.php?page=news_item&px=Broadcom-V3D-For-Mainline

**Comment by MightyCreak** [comment]
I'm still waiting for the `features.txt` file to list the VC4, VC5 and Vivante drivers. I haven't forgotten you :smile:

**Comment by austriancoder** [comment]
@MightyCreak Here we go :)

https://cgit.freedesktop.org/mesa/mesa/commit/?id=8dd26fa2f065e78f3204357d8b474656b9ea81db

**Comment by MightyCreak** [comment]
I'll add etnaviv as soon as I can find time (it's quite busy both in life and in the job right now ;) ).

**Comment by agx** [comment]
@MightyCreak thanks for looking into adding etnaviv.  Having it listed in it's current state will help to go after the other missing extensions ;)

**Comment by austriancoder** [comment]
@MightyCreak the driver will look sad for some time.. but we are working hard to improve it.

**Comment by MightyCreak** [comment]
I didn't forget you :wink: 
I just tested to add etnaviv and it works pretty well. That being said, I'm starting to miss some space to display all the drivers, but I won't bother for now, it'll be better on wide screens only for some time.

**Comment by MightyCreak** [comment]
Closing this PR, see #149 for explanations why.

**Pull request closed without merging**
