### PR TITLE
Attempt to create private_dir and log in base.php

### LINKED ISSUE #51: Initial setup should create log file
I get this message when running the initial setup:

    [2015-04-21 10:32:32] logger.ERROR: Error log /home/users/robin/mesamatrix/private mesamatrix.log is not writable! [] []

No log file is ever created, even if `private` exists. We need to create the private directory and then create the log file, before the logger is registered

### PR DESCRIPTION
**Pull request by Xenopathic**
Title says it all.

Fixes #51

### CODE REVIEW

**Comment by MightyCreak** [comment]
The main problem might be the rights of the dir and the log file. I'll try it on my server.

**Comment by Xenopathic** [comment]
The only thing the web interface touches in the private directory is the log file... Perhaps when it gets created we should print a message stating that the admin should check permissions on the log file to ensure the web server user can write to it?

**Comment by MightyCreak** [comment]
Yep, I would just like to know if there's a way to make this automatically, but I doubt that since all the other web applications I've seen ask the administrator to verify the rights of some specific dirs/files (like `chown www-data:www-data` for uploading dirs and `chmod 600` for private files).

Maybe we'll have to update the install section in the README.

(I'll try that tonight)

But overall, the commit seems fine ;)

**Comment by Xenopathic** [comment]
There is no way PHP can change the owner/group of the log file, unfortunately, even if it magically knew what to set it to. The best we can do is print the message/note in the README. There are two ways of doing it though - set the log as owned by the web user/web user group, or by using `setfacl` to give specifically the web user access to that log file. The relevant syntax is `setfacl -m u:www-data:rw private/mesamatrix.log`

**Comment by MightyCreak** [comment]
I'm not familiar with ACLs, is it just another name for regular file right management, or is it an abstraction layer handled by another software?

**Comment by Xenopathic** [comment]
@MightyCreak ACLs (or Access Control Lists) are advanced file permissions, which let you set read/write/execute permissions for a specific user or group, separate from the file owner and group. So I can allow my web server write access to the log file while it is still owned by me :smile:

**Comment by MightyCreak** [comment]
OK, sorry for the delay (again...). Why don't we create the `private` dir during the `setup` command instead? It seems to be the right place to do that, don't you think? I know that doing it in `base.php` prevent us from doing an update script, but since our project is not *that* renown, maybe we can take a shortcut here.

We could even write a few lines in the console after the setup is done, to ask the user to verify that the directory is accessible by the web server.

**Comment by Xenopathic** [comment]
`base.php` is executed before any other code, since it initialises things like the Config object and Logger. Unfortunately, that's the place that the private dir is needed. We could create the private dir in the setup command, but we'd still get errors when running the setup command (with no way to suppress them without some serious code foo)

**Comment by MightyCreak** [comment]
I see :+1:

**Pull request merged**
