### PR TITLE
Add new mesamatrixctl CLI tool

### PR DESCRIPTION
**Pull request by Xenopathic**
This commit replaces the individual `tools/*.php` files with a single
`mesamatrixctl` tool that uses Symfony Console. This means pretty console
output, less boilerplate code, more flexible output etc. All commands are
found in `lib/console/command/` and are registered from the static method
in `lib/console/commands.php` (Mesamatrix\Console\Commands::register()).

This commit also brings the 3rdparty directory, containing the following
git submodule links:
 * Symfony Console: https://github.com/symfony/Console
 * Symfony Process: https://github.com/symfony/Process
 * PHP-FIG Log:     https://github.com/php-fig/log

These submodules need to be initialised before use of Mesamatrix, by running `git submodule init` followed by `git submodule update`

In addition, the autoloader was slightly modified to use proper case for
class paths as per PSR-0, with compatibility for the current all-lowercase
paths. Other minor changes were made to other files also.

### CODE REVIEW

**Comment by Xenopathic** [comment]
Right, made some pretty major code changes. In order to set a default verbosity for the console output, I created a new class (`\Mesamatrix\Console\Application`) that inherits from the Symfony Console Application class, but in doing so I realised it makes sense to merge the command definitions into there (so no more `lib/console/commands.php`). In addition, I renamed the commands slightly to make more sense:

 * `git:fetch` has become `mesa:fetch`
 * `git:setup` has become `setup`
 * `git:parse` has become `parse`

This is because `setup` and `parse` are very generic, and while at the moment they only touch the Mesa git repo, at some point they might start doing things outside of that, so the best thing to do was to rename them so they aren't in the `git` category. Also, I felt that `git` was a bit arbitrary, so I renamed it `mesa`.

Oh, I updated the submodules too.

**Comment by MightyCreak** [comment]
Why not simply using `fetch` instead of `mesa:fetch`? If there's no plan for something else, I'd rather keep it simple, don't you think?

`setup`, `fetch` and `parse` are the three basic commands that our program needs.

**Comment by Xenopathic** [comment]
I didn't think `fetch` on its own meant very much - it really only makes sense in terms of the Mesa git repository. Compare to `setup` and `parse`, which are both very generic terms that don't apply to any specific part. Perhaps `update` would be better as a generic term, but in that case I'd suggest merging `mesa:fetch` with `parse` to make `update`. To be honest, there is little point in having both separately, other than for debugging purposes.

**Comment by MightyCreak** [comment]
I do understand what you're saying, but I'm still not convinced that there is a need now to complicate this kind of simple commands. Mesamatrix is all about the `mesa` git repository, so `fetch` is quite easy to understand from a user point of view, even though it's not semantically perfectly accurate.

Moreover, we can still decide that this is a v1 and if we feel the need later to have something more accurate, we can still do a v2 (it's not like if a thousand persons were using Mesamatrix right now, let's be honest ;)).

I do agree though that (as for `pull` command in git) we could add an `update` command that would do two commands in a row: `fetch` and `parse`. That would ease a lot the usability of Mesamatrix: no more long `cron` line or a shell script to write, just a simple `./mesamatrixctl update`.

**Pull request merged**
