### PR TITLE
Remove the last parse update date.

### PR DESCRIPTION
**Pull request by MightyCreak**
It's not very relevant for regular user since the website should simply
just work. The link to the complete log is still interesting though, so
I added it at the bottom of the list, with the link "More...".

@Xenopathic

### CODE REVIEW

**Comment by MightyCreak** [comment]
Actually it's even less relevant since the parsing isn't done if there are no commits ;)

**Comment by Xenopathic** [comment]
:-1: The user should always know when the server last did an update. If for whatever reason the server does not perform an update (say, cron broke), then the user may think that the information displayed is recent when it really isn't. It might be an idea to move that to the bottom though, out of the way.

**Comment by MightyCreak** [comment]
Actually, I never looked at this date, at the beginning I was displaying the date of the last commit, not the date of the last update on the server. When I want to know if the server did its job, I click on the link to the git log. Moreover, with the new "update if needed" feature, this date has even less meaning.

Among the applications (that I find well thought), I don't remember seeing the date of the last time the server has been updated. When an application works, it just works, the goal is that it works so well that the user doesn't think it could not work somehow ;)

And as a developer, of course, you need as much information as possible to verify and track any problem (that's why I let the date in the XML).

**Comment by Xenopathic** [comment]
There is one application that makes very heavy use of this sort of information: the last modified timestamp on files. It is crucial to know when a file was last updated in some way, and yes, while it is possible to compare the file contents from a (known) previous version and the current version to determine if there are any changes, I certainly don't think that is practical. In the same way, knowing when the Matrix was 'last modified' is important, since it is secondary information generated from a primary source.

**Comment by MightyCreak** [comment]
Let's find a compromise. What if we keep this date but write it at the bottom of the page instead of the very first line? I just don't think it should be the first information the user could watch. (After all, files timestamps are not displayed by default, but only when you ask for them)

**Comment by Xenopathic** [comment]
Yup, that'd be just fine. I agree with you - many users won't care about the last updated time, but some will, so we need to keep the information visible. Near the bottom would be sufficient :smile:

**Comment by MightyCreak** [comment]
:+1: I'll do that tonight then!

**Comment by MightyCreak** [comment]
@Xenopathic OK, I think it's fine now. I've re-written the description since now the date is not removed but just moved. You'll find the date in the new "How it works" sub-section at the end of the page.

**Comment by Xenopathic** [comment]
:+1:

**Pull request merged**
