### PR TITLE
Add percentage of completion for each GL version

### PR DESCRIPTION
**Pull request by MightyCreak**
@Xenopathic I add a percentage right after the GL version title, it represents the overall score for the version. I separated in 3 subjective sections:
* if equal 0: done
* if greater than 75: almost there
* if less than 75: not there yet

I tried to blend colors from red to green, but the result wasn't convincing: we couldn't clearly distinguish the "not done" from the "almost done", and "the very almost done" to "the completely done".

completion_colors

### CODE REVIEW

**Comment by Xenopathic** [comment]
Only problem is, we are going to have the same issue here as we did before - some drivers will never support newer GL extensions (like softpipe/llvmpipe), so the GL versions will never get higher than about 80%. I'd use a different heuristic - number of extensions with more than half of drivers supporting it? That way we avoid the problems with drivers that never support it, yet still get the benefit of seeing when drivers have support rather than just Mesa core.

**Comment by MightyCreak** [comment]
I thought of that, but I figured that since some mesa devs actually look frequently at this website, maybe they will see the problem and add some other tag in the file so we will know which extension will never be implemented.

I'm not very fond of the heuristic, it gives you a different number (maybe more realistic), but users won't understand how it works. Maybe I can simply give the `mesa` completion status.. how about that?

(I thought that, later, I could add an effect when the mouse is over the completion percentage so that it'll show the results by driver, so maybe showing only the `mesa` driver, having this feature in mind for the future, could work?)

**Comment by Xenopathic** [comment]
We should always provide a realistic estimate of completion progress. Using just Mesa completion would be better than it is at the moment, but we both know that just having core Mesa support doesn't mean anyone can actually use the feature. This is why I thought the simple heuristic would be good - it gives useful completion statistics (yes the user won't understand fully how it works, but they shouldn't need to, and if they do we have the source available :see_no_evil: ).

**Comment by MightyCreak** [comment]
Actually, I misread your proposal, I think it could be a good compromise (while waiting for more information on which drivers can handled which extensions), the only thing to add is an explanation. I'll use tipsy for that.

**Comment by MightyCreak** [comment]
@Xenopathic You can test it... it has the strange result that every unfinished OpenGL versions (except one) is inside 60-70%.

How about this heuristic: consider an extension implemented if there is at least one driver done for each vendor (except software)?

**Comment by Xenopathic** [comment]
I've noticed the heuristic isn't really very effective - it unfairly discounts the software and nv50/r600 drivers, since they cannot support some newer GL features. I agree with you - the `mesa` solution is more relevant, and works sufficiently well. The only situation where that heuristic will fail is when a GL version is complete for, say, i965, but not completed for any other drivers, then the percentage will show 100% even though a lot still needs to be done. But hey, it's an approximation by definition :smile:

Also, in future avoid using static variables like `$implementedRatio`. This is clearly a constant, so define it as one:

    const IMPLEMENTED_RATIO = 0.5;

Statics are bad :smile:

**Comment by MightyCreak** [comment]
I'm used to C++ and static consts variables, isn't there a problem with const variables in PHP though, I think I'm running a version of PHP (v5.4) on my server that doesn't handle it...

**Comment by MightyCreak** [comment]
Ok, I reset to 05f36b2 and added a help cursor and a new text line for tipsy.

**Comment by Xenopathic** [comment]
In C++, you can define any variable as a `const`, so that's why `static const` class members are a good way to go. In PHP, class constants are defined just with `const`, no static. A static member can be modified, which is clearly not `const`. And AFAIK, there's no problem with `const` in earlier PHP versions.

**Pull request merged**
