### PR TITLE
Add GitHub ribbon.

### PR DESCRIPTION
**Pull request by MightyCreak**
@Xenopathic Added a small orange ribbon on the top-right corner.

### CODE REVIEW

**Comment by Xenopathic** [comment]
Change the `position` to `fixed`, then it remains even while scrolling :smile:

**Comment by MightyCreak** [comment]
I did that but on mobile the ribbon is too invasive. I don't know how to do a "responsive" design like that (fixed on desktop and absolute on mobile), so I stayed with "absolute" ;)

**Comment by Xenopathic** [comment]
CSS `@media` selectors: https://css-tricks.com/css-media-queries/ :smile:

**Comment by MightyCreak** [comment]
Let's say we'll do that for another commit? ;)

**Comment by Xenopathic** [comment]
OK :+1:

**Pull request merged**
