### PR TITLE
Add VC4 driver

### PR DESCRIPTION
**Pull request by jasuarez**

### CODE REVIEW

**Comment by MightyCreak** [comment]
Thanks for the PR @jasuarez !

I don't see VC4 entries yet in the Mesa's features.txt, do you know if it will soon be merged?

**Comment by jasuarez** [comment]
Yes, there's a MR prepared (https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/8137)

**Comment by jasuarez** [comment]
> Yes, there's a MR prepared (https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/8137)

BTW, the plan is to merge that MR after this one, so the VC4 appears in the mesamatrix.net

**Comment by MightyCreak** [comment]
I don't know how my code would react if there's a driver that doesn't exist in the text file. I'll need to check that.

**Comment by MightyCreak** [comment]
Well, it seems the VC4 driver was already present in the features.txt file in the past (2019-11-08 apparently, and the whole grid seems to break down). I'll merge it, but it's possible I'll have to force a reparse after you merge your MR in mesa. We'll see!

**Comment by MightyCreak** [comment]
It's deployed!

**Pull request merged**
