### PR TITLE
Master list of AMD GPUs

### LINKED ISSUE #123: Some AMD GPUs don't work in the decoder ring
Some AMD GPUs like RX 480 and R5 M430 dont work in the decoder ring

### PR DESCRIPTION
**Pull request by SethBarberee**
Fixes #123.

**It is a stub but it's a good start!**

List has Radeon HD 2000 series and onwards.... Wanted to get some eyes on it.

### CODE REVIEW

**Comment by SethBarberee** [comment]
>  Some commercial names you give (e.g. R420, R670, ..) are not part of the families I've listed in drivers.js
Noted. I'll get that fixed to probably the R400, R600, etc. that you mentioned

**Comment by SethBarberee** [comment]
Ping

**Comment by MightyCreak** [comment]
Sorry for the delay, I'm fairly occupied with my job at the moment.

It's super cool! I think it'll help to give better results in the end.

So, now I need to modify the code and integrate this list in the results, unless you feel like you'd be able to do that?

**Comment by Olf0** [comment]
Oh, as correctly [pointed out in the PR proper](https://github.com/MightyCreak/mesamatrix/pull/135/files#diff-baee57dfc13dd14f197fade383bad9fccc04132b3de40c5abda9838c8a5451d7R2), almost "*all of HD 5000 Series and previous*" are missing and the two R100 entries are wrong.

All information is easily accessible, here is a description how to properly collect it:
1. https://www.x.org/wiki/RadeonFeature/#decoderringforengineeringvsmarketingnames
  This table provides the translation of "family names" in the first column (the ones Mesa and you care about) to "engineering names" in the second column (which is the indirection you have to use for step 2).  For this purpose this list is complete ("exhaustive"), but note that the list of "marketing names" in the third column is incomplete and may be contain incorrect entries!
2. https://en.wikipedia.org/wiki/List_of_AMD_graphics_processing_units#Radeon_7000_series ff.
  This and the following sections / tables do provide an exhaustive (and AFAICS correct) translation from the "engineering names" to the "marketing names" for all Radeon GPUs.

By the help of these two web-pages you can retrieve (and retrace) all ATI / AMD graphics card's product names ("marketing names") for a given "family name".
All it takes is a some time, a little effort and diligence.

**Comment by Olf0** [comment]
@MightyCreak: Did you close this PR because of it being stalled for four years?

**Comment by MightyCreak** [comment]
Oh! It seems that by removing the `master` branch (in favor of the more modern `main` naming convention), it also closed the PRs based on this branch.

You can reopen it if you want. I'm sorry about that 😕

**Comment by Olf0** [comment]
I can't, technically.  You can as administrator of this project and Seth can, because he posed this PR.

But I will not drive this PR forward, but might contribute to it, if someone does.

**Comment by MightyCreak** [comment]
@Olf0 I apparently can't reopen a PR whose source branch have been deleted, so I cloned it here: #241

**Pull request closed without merging**
