### PR TITLE
Center the whole page

### PR DESCRIPTION
**Pull request by MightyCreak**
@Xenopathic I tried to center the page and it actually is pretty nice!

Edit> It allows to align the leaderboard to the right of the column (second commit 5804a44).

### CODE REVIEW

**Comment by Xenopathic** [comment]
Slight issue - the width is too small to accommodate the full matrix:

screenshot - 140515 - 11 05 16

As a result, the leaderboard isn't *really* aligned to the right of the inner box, and the matrix isn't *really* centred.

**Comment by MightyCreak** [comment]
I see... It's because you have a font that is bigger than mine and the table's width depend on the font-size...

Here is what I've got here:
capture d ecran de 2015-05-14 08-02-13

I think the only thing I can do is extending the width of the table. But if you increase the font size, I can't do much ;)

**Comment by Xenopathic** [comment]
That's using the default font installed on my system, no special configuration. The width of the table should be determined automatically, not with an explicit width setting. AFAIK the flex box should just take the room it is given, without expanding the center box?

**Comment by MightyCreak** [comment]
I don't think it's doable, except by using a table for the whole layout, which is definitely not a good practice in HTML.

Most of the time, it's just a matter of giving enough space for the elements. I can try using em units instead of fixed pixels, it may adapt to any font size....

**Comment by MightyCreak** [comment]
@Xenopathic ok, I changed from `px` to `em`. What does it give you?

**Comment by MightyCreak** [comment]
is it ok with the new size unit?

**Comment by Xenopathic** [comment]
@MightyCreak Unfortunately, no :(

screenshot - 150515 - 13 48 26

Trying to set a size on the container will never work properly, you'll have to find a proper way of doing it.

**Comment by MightyCreak** [comment]
As far as I know, this is already the proper way of doing it :/
All the other sites does it like that.

**Comment by Xenopathic** [comment]
Well, other sites compress the inner content to fit the container (text wrapping etc). This obviously isn't possible here

**Comment by MightyCreak** [comment]
Yup, you're right... I think I didn't even try without the max-width at all.
I'll try that this week-end.

**Comment by Xenopathic** [comment]
Got it! And you'll love the simplicity:

```
body {
    display: flex;
    justify-content: center;
}
```

That's it. Really. You can even remove the `margin` from `#main`, and everything will stay centred! Neat, huh? I :heart: flexboxes :smiley:

**Comment by MightyCreak** [comment]
It seems just like the perfect solution! Nice catch! (I'll try this one at home, to be sure, before merging)

**Comment by MightyCreak** [comment]
Hmmm... it doesn't seem to work, it spans the page on the whole window.

**Comment by Xenopathic** [comment]
What browser are you using?

**Comment by MightyCreak** [comment]
Firefox

**Comment by MightyCreak** [comment]
Wait! Found it!

I wrote `flex: 1` instead of `display: flex` ^_^"

**Comment by Xenopathic** [comment]
Hehe... and it works now I take it?

**Comment by MightyCreak** [comment]
Since there was a bit of conflicts, I integrated everything locally (i.e. not using github)

**Pull request closed without merging**
