### PR TITLE
Master list of AMD GPUs

### PR DESCRIPTION
**Pull request by MightyCreak**
This is a clone of PR #135 which has been deleted inadvertently when migrating from `master` to `main` (I didn't know it would have this side-effect).

Here's a copy of the original description:\

> Fixes https://github.com/MightyCreak/mesamatrix/issues/123.
>
> **It is a stub but it's a good start!**
>
> List has Radeon HD 2000 series and onwards.... Wanted to get some eyes on it.

### CODE REVIEW

**Comment by mirh** [comment]
Can't you just parse this?
https://gitlab.freedesktop.org/mesa/mesa/blob/master/src/amd/common/amd_family.h

**Comment by MightyCreak** [comment]
@mirh i's a nice information to get the GPU families, but it doesn't provide the GPUs commercial names and it doesn't make a link between the commercial names, their GPU families and their drivers.

**Comment by mirh** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/drm/drm_pciids.h
https://gist.github.com/aras-p/980567299587e9616bd05a5496d70bcb
https://cgit.freedesktop.org/xorg/driver/xf86-video-ati/tree/src/pcidb/ati_pciids.csv
https://github.com/GPUOpen-Tools/device_info/blob/master/DeviceInfo.cpp

**Comment by Olf0** [comment]
@mirh, I also named sources (different ones) a while ago, which provide all necessary information to fully implement this, see https://github.com/MightyCreak/mesamatrix/pull/135#issuecomment-955603376.
I also pointed out some errors in the extant PR.

The crucial point is: Someone has to pursue completing this task.

**Pull request closed without merging**
