### PR TITLE
Add dozen (dzn) driver and rename "Emulation" to "Translation"

### PR DESCRIPTION
**Pull request by 1ace**
I've added these drivers to `features.txt` in [this MR](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/17796), but it hasn't been merged yet, so don't merge this one either for now :stuck_out_tongue_winking_eye:

Closes https://github.com/MightyCreak/mesamatrix/issues/235

### CODE REVIEW

**Comment by 1ace** [comment]
Oh btw, I've put `dzn` in the "software" vendor, but maybe you'd rather distinguish VK-on-CPU from VK-on-D3D12 and make them separate categories?

**Comment by sehraf** [comment]
is VK-on-D312-Warp a thing? :thinking:

**Comment by 1ace** [comment]
> Oh btw, I've put `dzn` in the "software" vendor, but maybe you'd rather distinguish VK-on-CPU from VK-on-D3D12 and make them separate categories?

Thinking about it more, I've split them, putting `dzn` into a new `"Layered"` "vendor".

> is VK-on-D312-Warp a thing? :thinking:

Technically I see no reason why not, but if you're going to use a software renderer anyway, you probably want to avoid adding a translation layer in between and just use lavapipe directly (barring bugs and missing features, but for the latter I'd be surprised if there were many vulkan features supported going through VK-on-D3D12-on-WARP and not with VK-on-lavapipe).

**Comment by 1ace** [comment]
Heads up, the MR has been merged, so these are now the official names for features.txt :)

**Comment by MightyCreak** [comment]
Sorry for the delay, i'll check that asap. As for the layered category, i'll need to check because it feels like it's the same as the "emulation" category. I know it's not really emulation, but neither is zink.

So maybe layered is a better name for all the drivers.

**Comment by 1ace** [comment]
To be more consistent with GL I've added dozen to the `Emulation` vendor, and I've added a second commit that renames it to `Layered` for both GL & VK.

Feel free to drop the second commit before merging, or to make/request any other modification :)

**Comment by archanox** [comment]
I just pulled in these changes and tested it locally, and it appears that `pvr` is missing a defined heading colour for the tables.

**Comment by phomes** [comment]
`pvr` was missing a heading color, and the style needed an update for the `Emulation` to `Layered` rename.

You can grab the two top commits from https://github.com/phomes/mesamatrix/tree/add-dzn-panvk-pvr to fix it

**Comment by MightyCreak** [comment]
Oh dang, sorry, I took my emails in the wrong order and merged a PR that partially fixed what you did here (I forgot dzn).

I'll check for dzn, I'm not sure about the term "Layered". I know we discussed about it somewhere here or on the dedicated Matrix room. I'll try to find it again.

**Comment by 1ace** [comment]
No worries about the mixup with #250/#253, it happens :slightly_smiling_face: 

Yeah, you're right that "everything is a layer in the end"; `translation driver` sounds good :+1:

**Pull request merged**
